development:
 adapter: postgresql
 encoding: unicode
 database: tabchip_development
 pool: 5
 username: tabchip_master
 password: tabchip1234
test:
 adapter: postgresql
 encoding: unicode
 database: tabchip_test
 pool: 5
 username: tabchip_master
 password: tabchip1234

production:
 adapter: postgresql
 encoding: unicode
 database: tabchip_production
 pool: 5
 username: tabchip_master
 password: tabchip1234